### ISSUE TITLE
Hackney version lock

### ISSUE THREAD

**Issue by rodrigues** [ymtszw/hipchat_elixir#1]
Hi there!

I see in https://github.com/ymtszw/hipchat_elixir/blob/master/mix.exs#L37 that this package requires specifically hackney `1.6.3`.

Could this version be relaxed, maybe to something like `~> 1.6.3`?

Thanks 👍🏼

**Comment by ymtszw** [comment]
(Just a side note: I might consider dropping hackney dependency someday, and use erlang's default [`httpc`](http://erlang.org/doc/apps/inets/http_client.html) for the sake of easier dependency management by users)

**Comment by ymtszw** [comment]
I will close this when I made a release with #2

**Comment by ymtszw** [comment]
Published as [0.3.0](https://hex.pm/packages/hipchat_elixir/0.3.0)
